[{"rule":"keyword","idx":4,"ln":3,"raw":"let","capt":[]},
{"rule":"vari","idx":8,"ln":3,"raw":"bla =","capt":["bla ","bla","="]},
{"rule":"num","idx":14,"ln":3,"raw":"56","capt":[null]},
{"rule":"op","idx":16,"ln":3,"raw":";","capt":[";"]},
{"rule":"comment","idx":20,"ln":3,"raw":"// a comment\r\n","capt":["\r\n"]},
{"rule":"keyword","idx":34,"ln":4,"raw":"let","capt":[]},
{"rule":"vari","idx":38,"ln":4,"raw":"text =","capt":["text ","text","="]},
{"rule":"str","idx":45,"ln":4,"raw":"\"hello /* cmt in str*/ world\"","capt":["hello \u000b\u000b\u000b\u000b\u000b\u000b\u000b\u000b\u000b\u000b\u000b\u000b\u000b\u000b\u000b world",null,null]},
{"rule":"comment","idx":52,"ln":4,"raw":"/* cmt in str*/","capt":[null]},
{"rule":"op","idx":74,"ln":4,"raw":".","capt":["."]},
{"rule":"wordlist","idx":75,"ln":4,"raw":" repeat","capt":[]},
{"rule":"opOpen","idx":82,"ln":4,"raw":"(","capt":["(",null,null,null],"type":0,"brace":{"raw":")","idx":94,"ln":4}},
{"rule":"num","idx":85,"ln":4,"raw":"45","capt":[null]},
{"rule":"op","idx":88,"ln":4,"raw":"+","capt":["+"]},
{"rule":"wordlist","idx":89,"ln":4,"raw":" bla ","capt":[]},
{"rule":"opClose","idx":94,"ln":4,"raw":")","capt":[")",null,null,null],"type":0,"brace":{"raw":"(","idx":82,"ln":4}},
{"rule":"op","idx":95,"ln":4,"raw":";","capt":[";"]},
{"rule":"keyword","idx":100,"ln":6,"raw":"function","capt":[]},
{"rule":"wordlist","idx":108,"ln":6,"raw":" test ","capt":[]},
{"rule":"comment","idx":114,"ln":6,"raw":"/* a bi comment with \"string\" */","capt":[null]},
{"rule":"opOpen","idx":147,"ln":6,"raw":"(","capt":["(",null,null,null],"type":0,"brace":{"raw":")","idx":163,"ln":6}},
{"rule":"vari","idx":149,"ln":6,"raw":"a=","capt":["a","a","="]},
{"rule":"num","idx":151,"ln":6,"raw":"45","capt":[null]},
{"rule":"op","idx":153,"ln":6,"raw":",","capt":[","]},
{"rule":"vari","idx":155,"ln":6,"raw":"b=","capt":["b","b","="]},
{"rule":"str","idx":157,"ln":6,"raw":"\"AAA\"","capt":["AAA",null,null]},
{"rule":"opClose","idx":163,"ln":6,"raw":")","capt":[")",null,null,null],"type":0,"brace":{"raw":"(","idx":147,"ln":6}},
{"rule":"opOpen","idx":164,"ln":6,"raw":"{","capt":[null,"{",null,null],"type":1,"brace":{"raw":"}","idx":302,"ln":10}},
{"rule":"keyword","idx":172,"ln":7,"raw":"let","capt":[]},
{"rule":"vari","idx":176,"ln":7,"raw":"obj =","capt":["obj ","obj","="]},
{"rule":"opOpen","idx":182,"ln":7,"raw":"{","capt":[null,"{",null,null],"type":1,"brace":{"raw":"}","idx":233,"ln":7}},
{"rule":"vari","idx":185,"ln":7,"raw":"name:","capt":["name","name",":"]},
{"rule":"str","idx":191,"ln":7,"raw":"\"Max\"","capt":["Max",null,null]},
{"rule":"op","idx":196,"ln":7,"raw":",","capt":[","]},
{"rule":"vari","idx":198,"ln":7,"raw":"age:","capt":["age","age",":"]},
{"rule":"opOpen","idx":204,"ln":7,"raw":"(","capt":["(",null,null,null],"type":0,"brace":{"raw":")","idx":209,"ln":7}},
{"rule":"num","idx":205,"ln":7,"raw":"42","capt":[null]},
{"rule":"op","idx":207,"ln":7,"raw":"+","capt":["+"]},
{"rule":"num","idx":208,"ln":7,"raw":"5","capt":[null]},
{"rule":"opClose","idx":209,"ln":7,"raw":")","capt":[")",null,null,null],"type":0,"brace":{"raw":"(","idx":204,"ln":7}},
{"rule":"op","idx":211,"ln":7,"raw":"*","capt":["*"]},
{"rule":"num","idx":213,"ln":7,"raw":"2","capt":[null]},
{"rule":"op","idx":214,"ln":7,"raw":",","capt":[","]},
{"rule":"vari","idx":216,"ln":7,"raw":"addr:","capt":["addr","addr",":"]},
{"rule":"opOpen","idx":221,"ln":7,"raw":"{","capt":[null,"{",null,null],"type":1,"brace":{"raw":"}","idx":230,"ln":7}},
{"rule":"vari","idx":223,"ln":7,"raw":"bbb:","capt":["bbb","bbb",":"]},
{"rule":"num","idx":227,"ln":7,"raw":"45","capt":[null]},
{"rule":"opClose","idx":230,"ln":7,"raw":"}","capt":[null,"}",null,null],"type":1,"brace":{"raw":"{","idx":221,"ln":7}},
{"rule":"opClose","idx":233,"ln":7,"raw":"}","capt":[null,"}",null,null],"type":1,"brace":{"raw":"{","idx":182,"ln":7}},
{"rule":"op","idx":234,"ln":7,"raw":";","capt":[";"]},
{"rule":"keyword","idx":242,"ln":8,"raw":"const","capt":[]},
{"rule":"vari","idx":248,"ln":8,"raw":"name =","capt":["name ","name","="]},
{"rule":"wordlist","idx":254,"ln":8,"raw":"  obj","capt":[]},
{"rule":"opOpen","idx":259,"ln":8,"raw":"[","capt":[null,null,"[",null],"type":2,"brace":{"raw":"]","idx":266,"ln":8}},
{"rule":"str","idx":260,"ln":8,"raw":"\"name\"","capt":["name",null,null]},
{"rule":"opClose","idx":266,"ln":8,"raw":"]","capt":[null,null,"]",null],"type":2,"brace":{"raw":"[","idx":259,"ln":8}},
{"rule":"op","idx":268,"ln":8,"raw":"+","capt":["+"]},
{"rule":"opOpen","idx":270,"ln":8,"raw":"(","capt":["(",null,null,null],"type":0,"brace":{"raw":")","idx":278,"ln":8}},
{"rule":"num","idx":271,"ln":8,"raw":"1","capt":[null]},
{"rule":"op","idx":272,"ln":8,"raw":"+","capt":["+"]},
{"rule":"opOpen","idx":273,"ln":8,"raw":"(","capt":["(",null,null,null],"type":0,"brace":{"raw":")","idx":277,"ln":8}},
{"rule":"num","idx":274,"ln":8,"raw":"2","capt":[null]},
{"rule":"op","idx":275,"ln":8,"raw":"+","capt":["+"]},
{"rule":"num","idx":276,"ln":8,"raw":"3","capt":[null]},
{"rule":"opClose","idx":277,"ln":8,"raw":")","capt":[")",null,null,null],"type":0,"brace":{"raw":"(","idx":273,"ln":8}},
{"rule":"opClose","idx":278,"ln":8,"raw":")","capt":[")",null,null,null],"type":0,"brace":{"raw":"(","idx":270,"ln":8}},
{"rule":"op","idx":279,"ln":8,"raw":";","capt":[";"]},
{"rule":"keyword","idx":287,"ln":9,"raw":"return","capt":[]},
{"rule":"wordlist","idx":293,"ln":9,"raw":" a ","capt":[]},
{"rule":"op","idx":296,"ln":9,"raw":"+","capt":["+"]},
{"rule":"wordlist","idx":297,"ln":9,"raw":" b","capt":[]},
{"rule":"op","idx":299,"ln":9,"raw":";","capt":[";"]},
{"rule":"opClose","idx":302,"ln":10,"raw":"}","capt":[null,"}",null,null],"type":1,"brace":{"raw":"{","idx":164,"ln":6}}]
