[{"rule":"keyword","idx":0,"ln":1,"raw":"let","capt":[]},
{"rule":"vari","idx":4,"ln":1,"raw":"name =","capt":["name","="]},
{"rule":"str","idx":11,"ln":1,"raw":"\"foo\"","capt":["foo",null,null]},
{"rule":"op","idx":16,"ln":1,"raw":";","capt":[";"]},
{"rule":"keyword","idx":21,"ln":3,"raw":"const","capt":[]},
{"rule":"vari","idx":27,"ln":3,"raw":"age =","capt":["age","="]},
{"rule":"num","idx":33,"ln":3,"raw":"42","capt":[null]},
{"rule":"op","idx":35,"ln":3,"raw":";","capt":[";"]},
{"rule":"keyword","idx":42,"ln":6,"raw":"function","capt":[]},
{"rule":"wordlist","idx":50,"ln":6,"raw":" isOldEnough","capt":[]},
{"rule":"opOpen","idx":62,"ln":6,"raw":"(","capt":["(",null,null],"type":0},
{"rule":"wordlist","idx":63,"ln":6,"raw":"person","capt":[]},
{"rule":"opClose","idx":69,"ln":6,"raw":")","capt":[")",null,null],"type":0},
{"rule":"opOpen","idx":70,"ln":6,"raw":"{","capt":[null,"{",null],"type":1},
{"rule":"keyword","idx":79,"ln":8,"raw":"const","capt":[]},
{"rule":"vari","idx":85,"ln":8,"raw":"obj =","capt":["obj","="]},
{"rule":"opOpen","idx":91,"ln":8,"raw":"{","capt":[null,"{",null],"type":1},
{"rule":"vari","idx":93,"ln":8,"raw":"name:","capt":["name",":"]},
{"rule":"str","idx":98,"ln":8,"raw":"\"yourName\"","capt":["yourName",null,null]},
{"rule":"op","idx":108,"ln":8,"raw":",","capt":[","]},
{"rule":"vari","idx":110,"ln":8,"raw":"list:","capt":["list",":"]},
{"rule":"opOpen","idx":116,"ln":8,"raw":"[","capt":[null,null,"["],"type":2},
{"rule":"num","idx":118,"ln":8,"raw":"1","capt":[null]},
{"rule":"op","idx":119,"ln":8,"raw":",","capt":[","]},
{"rule":"num","idx":120,"ln":8,"raw":"2","capt":[null]},
{"rule":"op","idx":121,"ln":8,"raw":",","capt":[","]},
{"rule":"num","idx":122,"ln":8,"raw":"3.14","capt":[null]},
{"rule":"opClose","idx":127,"ln":8,"raw":"]","capt":[null,null,"]"],"type":2},
{"rule":"opClose","idx":129,"ln":8,"raw":"}","capt":[null,"}",null],"type":1},
{"rule":"keyword","idx":138,"ln":10,"raw":"if","capt":[]},
{"rule":"opOpen","idx":140,"ln":10,"raw":"(","capt":["(",null,null],"type":0},
{"rule":"wordlist","idx":141,"ln":10,"raw":"person","capt":[]},
{"rule":"op","idx":147,"ln":10,"raw":".","capt":["."]},
{"rule":"wordlist","idx":148,"ln":10,"raw":"age","capt":[]},
{"rule":"op","idx":151,"ln":10,"raw":">","capt":[">"]},
{"rule":"num","idx":152,"ln":10,"raw":"5","capt":[null]},
{"rule":"opClose","idx":153,"ln":10,"raw":")","capt":[")",null,null],"type":0},
{"rule":"keyword","idx":155,"ln":10,"raw":"return","capt":[]},
{"rule":"opClose","idx":164,"ln":11,"raw":"}","capt":[null,"}",null],"type":1},
{"rule":"keyword","idx":169,"ln":13,"raw":"const","capt":[]},
{"rule":"vari","idx":175,"ln":13,"raw":"rndNums =","capt":["rndNums","="]},
{"rule":"opOpen","idx":185,"ln":13,"raw":"[","capt":[null,null,"["],"type":2},
{"rule":"num","idx":187,"ln":13,"raw":"1","capt":[null]},
{"rule":"op","idx":188,"ln":13,"raw":",","capt":[","]},
{"rule":"opOpen","idx":190,"ln":13,"raw":"(","capt":["(",null,null],"type":0},
{"rule":"num","idx":191,"ln":13,"raw":"2","capt":[null]},
{"rule":"op","idx":192,"ln":13,"raw":"+","capt":["+"]},
{"rule":"num","idx":193,"ln":13,"raw":"2","capt":[null]},
{"rule":"opClose","idx":194,"ln":13,"raw":")","capt":[")",null,null],"type":0},
{"rule":"op","idx":195,"ln":13,"raw":",","capt":[","]},
{"rule":"num","idx":197,"ln":13,"raw":"98","capt":[null]},
{"rule":"opClose","idx":201,"ln":13,"raw":"]","capt":[null,null,"]"],"type":2},
{"rule":"op","idx":202,"ln":13,"raw":";","capt":[";"]}]
