[{"rule":"op","idx":0,"ln":1,"raw":"<","capt":["<"]},
{"rule":"wordlist","idx":1,"ln":1,"raw":"body","capt":[]},
{"rule":"op","idx":5,"ln":1,"raw":">","capt":[">"]},
{"rule":"op","idx":8,"ln":2,"raw":"<","capt":["<"]},
{"rule":"wordlist","idx":9,"ln":2,"raw":"script defer","capt":[]},
{"rule":"op","idx":21,"ln":2,"raw":">","capt":[">"]},
{"rule":"keyword","idx":26,"ln":4,"raw":"let","capt":[]},
{"rule":"vari","idx":30,"ln":4,"raw":"name =","capt":["name","="]},
{"rule":"str","idx":37,"ln":4,"raw":"\"foo\"","capt":["foo",null,null]},
{"rule":"op","idx":42,"ln":4,"raw":";","capt":[";"]},
{"rule":"keyword","idx":47,"ln":6,"raw":"const","capt":[]},
{"rule":"vari","idx":53,"ln":6,"raw":"age =","capt":["age","="]},
{"rule":"num","idx":59,"ln":6,"raw":"42","capt":[null]},
{"rule":"op","idx":61,"ln":6,"raw":";","capt":[";"]},
{"rule":"keyword","idx":68,"ln":9,"raw":"function","capt":[]},
{"rule":"wordlist","idx":76,"ln":9,"raw":" isOldEnough","capt":[]},
{"rule":"opOpen","idx":88,"ln":9,"raw":"(","capt":["(",null,null]},
{"rule":"wordlist","idx":89,"ln":9,"raw":"person","capt":[]},
{"rule":"opClose","idx":95,"ln":9,"raw":")","capt":[")",null,null]},
{"rule":"opOpen","idx":96,"ln":9,"raw":"{","capt":[null,"{",null]},
{"rule":"keyword","idx":103,"ln":10,"raw":"if","capt":[]},
{"rule":"opOpen","idx":105,"ln":10,"raw":"(","capt":["(",null,null]},
{"rule":"wordlist","idx":106,"ln":10,"raw":"person","capt":[]},
{"rule":"op","idx":112,"ln":10,"raw":".","capt":["."]},
{"rule":"wordlist","idx":113,"ln":10,"raw":"age","capt":[]},
{"rule":"op","idx":116,"ln":10,"raw":">","capt":[">"]},
{"rule":"num","idx":117,"ln":10,"raw":"5","capt":[null]},
{"rule":"opClose","idx":118,"ln":10,"raw":")","capt":[")",null,null]},
{"rule":"wordlist","idx":119,"ln":10,"raw":" return \r\n","capt":[]},
{"rule":"opClose","idx":129,"ln":11,"raw":"}","capt":[null,"}",null]},
{"rule":"keyword","idx":134,"ln":13,"raw":"const","capt":[]},
{"rule":"vari","idx":140,"ln":13,"raw":"rndNums =","capt":["rndNums","="]},
{"rule":"opOpen","idx":150,"ln":13,"raw":"[","capt":[null,null,"["]},
{"rule":"num","idx":152,"ln":13,"raw":"1","capt":[null]},
{"rule":"op","idx":153,"ln":13,"raw":",","capt":[","]},
{"rule":"opOpen","idx":155,"ln":13,"raw":"(","capt":["(",null,null]},
{"rule":"num","idx":156,"ln":13,"raw":"2","capt":[null]},
{"rule":"op","idx":157,"ln":13,"raw":"+","capt":["+"]},
{"rule":"num","idx":158,"ln":13,"raw":"2","capt":[null]},
{"rule":"opClose","idx":159,"ln":13,"raw":")","capt":[")",null,null]},
{"rule":"op","idx":160,"ln":13,"raw":",","capt":[","]},
{"rule":"num","idx":162,"ln":13,"raw":"98","capt":[null]},
{"rule":"opClose","idx":166,"ln":13,"raw":"]","capt":[null,null,"]"]},
{"rule":"op","idx":167,"ln":13,"raw":";","capt":[";"]},
{"rule":"keyword","idx":172,"ln":15,"raw":"let","capt":[]},
{"rule":"vari","idx":176,"ln":15,"raw":"El =","capt":["El","="]},
{"rule":"wordlist","idx":180,"ln":15,"raw":" HTMLElement","capt":[]},
{"rule":"op","idx":192,"ln":15,"raw":".","capt":["."]},
{"rule":"wordlist","idx":193,"ln":15,"raw":"prototype","capt":[]},
{"rule":"op","idx":202,"ln":15,"raw":";","capt":[";"]},
{"rule":"vari","idx":210,"ln":15,"raw":"El=","capt":["El","="]},
{"rule":"wordlist","idx":213,"ln":15,"raw":"null","capt":[]},
{"rule":"op","idx":217,"ln":15,"raw":";","capt":[";"]},
{"rule":"keyword","idx":220,"ln":16,"raw":"let","capt":[]},
{"rule":"vari","idx":224,"ln":16,"raw":"JsonEml =","capt":["JsonEml","="]},
{"rule":"opOpen","idx":235,"ln":16,"raw":"[","capt":[null,null,"["]},
{"rule":"str","idx":236,"ln":16,"raw":"\"tag\"","capt":["tag",null,null]},
{"rule":"op","idx":241,"ln":16,"raw":",","capt":[","]},
{"rule":"opOpen","idx":242,"ln":16,"raw":"{","capt":[null,"{",null]},
{"rule":"vari","idx":243,"ln":16,"raw":"attr:","capt":["attr",":"]},
{"rule":"str","idx":248,"ln":16,"raw":"\"val\"","capt":["val",null,null]},
{"rule":"opClose","idx":253,"ln":16,"raw":"}","capt":[null,"}",null]},
{"rule":"op","idx":254,"ln":16,"raw":",","capt":[","]},
{"rule":"opOpen","idx":255,"ln":16,"raw":"[","capt":[null,null,"["]},
{"rule":"str","idx":256,"ln":16,"raw":"\"txt1\"","capt":["txt1",null,null]},
{"rule":"op","idx":262,"ln":16,"raw":",","capt":[","]},
{"rule":"wordlist","idx":263,"ln":16,"raw":" El ","capt":[]},
{"rule":"op","idx":267,"ln":16,"raw":",","capt":[","]},
{"rule":"str","idx":268,"ln":16,"raw":"\"txt2\"","capt":["txt2",null,null]},
{"rule":"opClose","idx":274,"ln":16,"raw":"]","capt":[null,null,"]"]},
{"rule":"op","idx":275,"ln":16,"raw":",","capt":[","]},
{"rule":"opClose","idx":278,"ln":16,"raw":"]","capt":[null,null,"]"]},
{"rule":"op","idx":279,"ln":16,"raw":";","capt":[";"]},
{"rule":"vari","idx":282,"ln":16,"raw":"JsonEml=","capt":["JsonEml","="]},
{"rule":"wordlist","idx":290,"ln":16,"raw":"null","capt":[]},
{"rule":"op","idx":294,"ln":16,"raw":";","capt":[";"]},
{"rule":"comment","idx":301,"ln":19,"raw":"/*  JSONML API fn for less boilerplate DOM creation  */","capt":[null]},
{"rule":"keyword","idx":358,"ln":20,"raw":"function","capt":[]},
{"rule":"wordlist","idx":366,"ln":20,"raw":" $New","capt":[]},
{"rule":"opOpen","idx":371,"ln":20,"raw":"(","capt":["(",null,null]},
{"rule":"vari","idx":372,"ln":20,"raw":"tag=","capt":["tag","="]},
{"rule":"str","idx":376,"ln":20,"raw":"\"\"","capt":["",null,null]},
{"rule":"op","idx":378,"ln":20,"raw":",","capt":[","]},
{"rule":"vari","idx":379,"ln":20,"raw":"attrs=","capt":["attrs","="]},
{"rule":"opOpen","idx":385,"ln":20,"raw":"{","capt":[null,"{",null]},
{"rule":"opClose","idx":386,"ln":20,"raw":"}","capt":[null,"}",null]},
{"rule":"op","idx":387,"ln":20,"raw":",","capt":[","]},
{"rule":"vari","idx":388,"ln":20,"raw":"chi=","capt":["chi","="]},
{"rule":"wordlist","idx":392,"ln":20,"raw":"JsonEml","capt":[]},
{"rule":"op","idx":399,"ln":20,"raw":",","capt":[","]},
{"rule":"vari","idx":400,"ln":20,"raw":"pa=","capt":["pa","="]},
{"rule":"wordlist","idx":403,"ln":20,"raw":"El","capt":[]},
{"rule":"opClose","idx":405,"ln":20,"raw":")","capt":[")",null,null]},
{"rule":"opOpen","idx":406,"ln":20,"raw":"{","capt":[null,"{",null]},
{"rule":"keyword","idx":413,"ln":21,"raw":"const","capt":[]},
{"rule":"vari","idx":419,"ln":21,"raw":"el =","capt":["el","="]},
{"rule":"wordlist","idx":423,"ln":21,"raw":" document","capt":[]},
{"rule":"op","idx":432,"ln":21,"raw":".","capt":["."]},
{"rule":"wordlist","idx":433,"ln":21,"raw":"createElement","capt":[]},
{"rule":"opOpen","idx":446,"ln":21,"raw":"(","capt":["(",null,null]},
{"rule":"wordlist","idx":447,"ln":21,"raw":"tag","capt":[]},
{"rule":"opClose","idx":450,"ln":21,"raw":")","capt":[")",null,null]},
{"rule":"op","idx":451,"ln":21,"raw":";","capt":[";"]},
{"rule":"keyword","idx":460,"ln":23,"raw":"if","capt":[]},
{"rule":"opOpen","idx":462,"ln":23,"raw":"(","capt":["(",null,null]},
{"rule":"wordlist","idx":463,"ln":23,"raw":"attrs","capt":[]},
{"rule":"opClose","idx":468,"ln":23,"raw":")","capt":[")",null,null]},
{"rule":"keyword","idx":470,"ln":23,"raw":"for","capt":[]},
{"rule":"opOpen","idx":473,"ln":23,"raw":"(","capt":["(",null,null]},
{"rule":"keyword","idx":474,"ln":23,"raw":"const","capt":[]},
{"rule":"wordlist","idx":479,"ln":23,"raw":" att in attrs","capt":[]},
{"rule":"opClose","idx":492,"ln":23,"raw":")","capt":[")",null,null]},
{"rule":"wordlist","idx":493,"ln":23,"raw":"  el","capt":[]},
{"rule":"op","idx":497,"ln":23,"raw":".","capt":["."]},
{"rule":"wordlist","idx":498,"ln":23,"raw":"setAttribute","capt":[]},
{"rule":"opOpen","idx":510,"ln":23,"raw":"(","capt":["(",null,null]},
{"rule":"wordlist","idx":511,"ln":23,"raw":"att","capt":[]},
{"rule":"op","idx":514,"ln":23,"raw":",","capt":[","]},
{"rule":"wordlist","idx":515,"ln":23,"raw":"attrs","capt":[]},
{"rule":"opOpen","idx":520,"ln":23,"raw":"[","capt":[null,null,"["]},
{"rule":"wordlist","idx":521,"ln":23,"raw":"att","capt":[]},
{"rule":"opClose","idx":524,"ln":23,"raw":"]","capt":[null,null,"]"]},
{"rule":"opClose","idx":525,"ln":23,"raw":")","capt":[")",null,null]},
{"rule":"op","idx":526,"ln":23,"raw":";","capt":[";"]},
{"rule":"keyword","idx":535,"ln":25,"raw":"if","capt":[]},
{"rule":"opOpen","idx":537,"ln":25,"raw":"(","capt":["(",null,null]},
{"rule":"wordlist","idx":538,"ln":25,"raw":"chi","capt":[]},
{"rule":"op","idx":541,"ln":25,"raw":"?","capt":["?"]},
{"rule":"op","idx":542,"ln":25,"raw":".","capt":["."]},
{"rule":"wordlist","idx":543,"ln":25,"raw":"map","capt":[]},
{"rule":"opClose","idx":546,"ln":25,"raw":")","capt":[")",null,null]},
{"rule":"wordlist","idx":547,"ln":25,"raw":"  el","capt":[]},
{"rule":"op","idx":551,"ln":25,"raw":".","capt":["."]},
{"rule":"wordlist","idx":552,"ln":25,"raw":"append","capt":[]},
{"rule":"opOpen","idx":558,"ln":25,"raw":"(","capt":["(",null,null]},
{"rule":"op","idx":559,"ln":25,"raw":"..","capt":["."]},
{"rule":"op","idx":561,"ln":25,"raw":".","capt":["."]},
{"rule":"wordlist","idx":562,"ln":25,"raw":"chi","capt":[]},
{"rule":"op","idx":565,"ln":25,"raw":".","capt":["."]},
{"rule":"wordlist","idx":566,"ln":25,"raw":"map","capt":[]},
{"rule":"opOpen","idx":569,"ln":25,"raw":"(","capt":["(",null,null]},
{"rule":"vari","idx":571,"ln":25,"raw":"c=","capt":["c","="]},
{"rule":"op","idx":573,"ln":25,"raw":">","capt":[">"]},
{"rule":"wordlist","idx":574,"ln":25,"raw":"  c","capt":[]},
{"rule":"op","idx":577,"ln":25,"raw":".","capt":["."]},
{"rule":"wordlist","idx":578,"ln":25,"raw":"map","capt":[]},
{"rule":"op","idx":581,"ln":25,"raw":"?","capt":["?"]},
{"rule":"wordlist","idx":582,"ln":25,"raw":" $New","capt":[]},
{"rule":"opOpen","idx":587,"ln":25,"raw":"(","capt":["(",null,null]},
{"rule":"op","idx":588,"ln":25,"raw":"..","capt":["."]},
{"rule":"op","idx":590,"ln":25,"raw":".","capt":["."]},
{"rule":"wordlist","idx":591,"ln":25,"raw":"c","capt":[]},
{"rule":"opClose","idx":592,"ln":25,"raw":")","capt":[")",null,null]},
{"rule":"op","idx":594,"ln":25,"raw":":","capt":[":"]},
{"rule":"wordlist","idx":595,"ln":25,"raw":"c  ","capt":[]},
{"rule":"opClose","idx":598,"ln":25,"raw":")","capt":[")",null,null]},
{"rule":"opClose","idx":599,"ln":25,"raw":")","capt":[")",null,null]},
{"rule":"op","idx":600,"ln":25,"raw":";","capt":[";"]},
{"rule":"keyword","idx":609,"ln":27,"raw":"if","capt":[]},
{"rule":"opOpen","idx":611,"ln":27,"raw":"(","capt":["(",null,null]},
{"rule":"wordlist","idx":612,"ln":27,"raw":"pa","capt":[]},
{"rule":"opClose","idx":614,"ln":27,"raw":")","capt":[")",null,null]},
{"rule":"vari","idx":617,"ln":27,"raw":"pa=","capt":["pa","="]},
{"rule":"op","idx":620,"ln":27,"raw":"=","capt":["="]},
{"rule":"num","idx":621,"ln":27,"raw":"1","capt":[null]},
{"rule":"op","idx":622,"ln":27,"raw":"?","capt":["?"]},
{"rule":"vari","idx":623,"ln":27,"raw":"pa=","capt":["pa","="]},
{"rule":"vari","idx":626,"ln":27,"raw":"document.body:","capt":["body",":"]},
{"rule":"num","idx":640,"ln":27,"raw":"0","capt":[null]},
{"rule":"op","idx":641,"ln":27,"raw":",","capt":[","]},
{"rule":"wordlist","idx":642,"ln":27,"raw":"  pa","capt":[]},
{"rule":"op","idx":646,"ln":27,"raw":".","capt":["."]},
{"rule":"wordlist","idx":647,"ln":27,"raw":"append","capt":[]},
{"rule":"opOpen","idx":653,"ln":27,"raw":"(","capt":["(",null,null]},
{"rule":"wordlist","idx":654,"ln":27,"raw":"el","capt":[]},
{"rule":"opClose","idx":656,"ln":27,"raw":")","capt":[")",null,null]},
{"rule":"op","idx":657,"ln":27,"raw":";","capt":[";"]},
{"rule":"wordlist","idx":658,"ln":27,"raw":"\r\n\r\n    return el","capt":[]},
{"rule":"op","idx":675,"ln":29,"raw":";","capt":[";"]},
{"rule":"opClose","idx":678,"ln":30,"raw":"}","capt":[null,"}",null]},
{"rule":"keyword","idx":683,"ln":32,"raw":"const","capt":[]},
{"rule":"vari","idx":689,"ln":32,"raw":"ulRd =","capt":["ulRd","="]},
{"rule":"wordlist","idx":695,"ln":32,"raw":" $New","capt":[]},
{"rule":"opOpen","idx":700,"ln":32,"raw":"(","capt":["(",null,null]},
{"rule":"str","idx":701,"ln":32,"raw":"\"ul\"","capt":["ul",null,null]},
{"rule":"op","idx":705,"ln":32,"raw":",","capt":[","]},
{"rule":"opOpen","idx":706,"ln":32,"raw":"{","capt":[null,"{",null]},
{"rule":"vari","idx":707,"ln":32,"raw":"id:","capt":["id",":"]},
{"rule":"str","idx":710,"ln":32,"raw":"\"myUl\"","capt":["myUl",null,null]},
{"rule":"opClose","idx":716,"ln":32,"raw":"}","capt":[null,"}",null]},
{"rule":"op","idx":717,"ln":32,"raw":",","capt":[","]},
{"rule":"num","idx":718,"ln":32,"raw":"0","capt":[null]},
{"rule":"op","idx":719,"ln":32,"raw":",","capt":[","]},
{"rule":"wordlist","idx":720,"ln":32,"raw":"document","capt":[]},
{"rule":"op","idx":728,"ln":32,"raw":".","capt":["."]},
{"rule":"wordlist","idx":729,"ln":32,"raw":"body","capt":[]},
{"rule":"opClose","idx":733,"ln":32,"raw":")","capt":[")",null,null]},
{"rule":"op","idx":734,"ln":32,"raw":";","capt":[";"]},
{"rule":"keyword","idx":741,"ln":35,"raw":"for","capt":[]},
{"rule":"opOpen","idx":744,"ln":35,"raw":"(","capt":["(",null,null]},
{"rule":"keyword","idx":745,"ln":35,"raw":"let","capt":[]},
{"rule":"vari","idx":749,"ln":35,"raw":"i=","capt":["i","="]},
{"rule":"num","idx":751,"ln":35,"raw":"0","capt":[null]},
{"rule":"op","idx":752,"ln":35,"raw":";","capt":[";"]},
{"rule":"wordlist","idx":753,"ln":35,"raw":" i","capt":[]},
{"rule":"op","idx":755,"ln":35,"raw":"<","capt":["<"]},
{"rule":"wordlist","idx":756,"ln":35,"raw":"rndNums","capt":[]},
{"rule":"op","idx":763,"ln":35,"raw":".","capt":["."]},
{"rule":"wordlist","idx":764,"ln":35,"raw":"length","capt":[]},
{"rule":"op","idx":770,"ln":35,"raw":";","capt":[";"]},
{"rule":"wordlist","idx":771,"ln":35,"raw":" i","capt":[]},
{"rule":"op","idx":773,"ln":35,"raw":"++","capt":["+"]},
{"rule":"opClose","idx":775,"ln":35,"raw":")","capt":[")",null,null]},
{"rule":"opOpen","idx":776,"ln":35,"raw":"{","capt":[null,"{",null]},
{"rule":"wordlist","idx":777,"ln":35,"raw":"\r\n    $New","capt":[]},
{"rule":"opOpen","idx":787,"ln":36,"raw":"(","capt":["(",null,null]},
{"rule":"str","idx":789,"ln":36,"raw":"\"li\"","capt":["li",null,null]},
{"rule":"op","idx":793,"ln":36,"raw":",","capt":[","]},
{"rule":"opOpen","idx":797,"ln":36,"raw":"{","capt":[null,"{",null]},
{"rule":"vari","idx":799,"ln":36,"raw":"id:","capt":["id",":"]},
{"rule":"str","idx":802,"ln":36,"raw":"`id-${i}`","capt":[null,null,"id-${i}"]},
{"rule":"op","idx":811,"ln":36,"raw":",","capt":[","]},
{"rule":"str","idx":813,"ln":36,"raw":"\"data-i\"","capt":["data-i",null,null]},
{"rule":"op","idx":821,"ln":36,"raw":":","capt":[":"]},
{"rule":"wordlist","idx":822,"ln":36,"raw":"i ","capt":[]},
{"rule":"opClose","idx":824,"ln":36,"raw":"}","capt":[null,"}",null]},
{"rule":"op","idx":825,"ln":36,"raw":",","capt":[","]},
{"rule":"opOpen","idx":837,"ln":37,"raw":"[","capt":[null,null,"["]},
{"rule":"str","idx":839,"ln":37,"raw":"\"my list text \"","capt":["my list text ",null,null]},
{"rule":"op","idx":854,"ln":37,"raw":",","capt":[","]},
{"rule":"opOpen","idx":857,"ln":37,"raw":"[","capt":[null,null,"["]},
{"rule":"str","idx":858,"ln":37,"raw":"\"b\"","capt":["b",null,null]},
{"rule":"op","idx":861,"ln":37,"raw":",","capt":[","]},
{"rule":"num","idx":862,"ln":37,"raw":"0","capt":[null]},
{"rule":"op","idx":863,"ln":37,"raw":",","capt":[","]},
{"rule":"opOpen","idx":864,"ln":37,"raw":"[","capt":[null,null,"["]},
{"rule":"str","idx":865,"ln":37,"raw":"\"bold \"","capt":["bold ",null,null]},
{"rule":"op","idx":872,"ln":37,"raw":",","capt":[","]},
{"rule":"wordlist","idx":873,"ln":37,"raw":"i","capt":[]},
{"rule":"op","idx":874,"ln":37,"raw":",","capt":[","]},
{"rule":"str","idx":875,"ln":37,"raw":"\" \"","capt":[" ",null,null]},
{"rule":"opClose","idx":878,"ln":37,"raw":"]","capt":[null,null,"]"]},
{"rule":"opClose","idx":880,"ln":37,"raw":"]","capt":[null,null,"]"]},
{"rule":"op","idx":882,"ln":37,"raw":",","capt":[","]},
{"rule":"wordlist","idx":883,"ln":37,"raw":" Math","capt":[]},
{"rule":"op","idx":888,"ln":37,"raw":".","capt":["."]},
{"rule":"wordlist","idx":889,"ln":37,"raw":"random","capt":[]},
{"rule":"opOpen","idx":895,"ln":37,"raw":"(","capt":["(",null,null]},
{"rule":"opClose","idx":896,"ln":37,"raw":")","capt":[")",null,null]},
{"rule":"op","idx":897,"ln":37,"raw":".","capt":["."]},
{"rule":"wordlist","idx":898,"ln":37,"raw":"toString","capt":[]},
{"rule":"opOpen","idx":906,"ln":37,"raw":"(","capt":["(",null,null]},
{"rule":"num","idx":907,"ln":37,"raw":"36","capt":[null]},
{"rule":"opClose","idx":909,"ln":37,"raw":")","capt":[")",null,null]},
{"rule":"op","idx":910,"ln":37,"raw":".","capt":["."]},
{"rule":"wordlist","idx":911,"ln":37,"raw":"slice","capt":[]},
{"rule":"opOpen","idx":916,"ln":37,"raw":"(","capt":["(",null,null]},
{"rule":"num","idx":917,"ln":37,"raw":"2","capt":[null]},
{"rule":"op","idx":918,"ln":37,"raw":",","capt":[","]},
{"rule":"num","idx":919,"ln":37,"raw":"8","capt":[null]},
{"rule":"opClose","idx":920,"ln":37,"raw":")","capt":[")",null,null]},
{"rule":"opClose","idx":924,"ln":37,"raw":"]","capt":[null,null,"]"]},
{"rule":"op","idx":925,"ln":37,"raw":",","capt":[","]},
{"rule":"wordlist","idx":926,"ln":37,"raw":"\r\n        ulRd\r\n    ","capt":[]},
{"rule":"opClose","idx":946,"ln":39,"raw":")","capt":[")",null,null]},
{"rule":"opClose","idx":949,"ln":40,"raw":"}","capt":[null,"}",null]},
{"rule":"op","idx":954,"ln":42,"raw":"<","capt":["<"]},
{"rule":"op","idx":955,"ln":42,"raw":"/","capt":["/"]},
{"rule":"wordlist","idx":956,"ln":42,"raw":"script","capt":[]},
{"rule":"op","idx":962,"ln":42,"raw":">","capt":[">"]}]
